### ISSUE TITLE
USER STORY: Pick expiry poll date

### ISSUE THREAD

**Issue by MartinaP87** [MartinaP87/My-first-Agile-project#5]
As an **administrator** I can **pick the expiry date while publishing the poll** so that **the poll automatically hides**

## Acceptance Criteria:
- The poll should disappear at 11:59PM on the target date
- The real estate of the "Poll" should be reserved on the home page. A message that says "Stay Tuned, a new poll is coming soon" should appear if non other Poll is active
- The administrator expiry date should be at least 3 days after the current date

## Tasks:
- [x] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: show "Stay Tuned, a new poll is coming soon"
- [ ] Create a JavaScript function to validate the expiry date is at least after 3 days
